name: jr_case_boilerplate
description: "A new Flutter project."

publish_to: 'none' 



environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  lottie: ^3.3.1
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.4
  permission_handler: ^11.0.1

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/animations/
    


  
